version: '3.8'

services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build: 
      context: .
    ports:
      - 8080:80
  backend:
    container_name: docker-django-c
    build: 
      context: .
      dockerfile: django_app/Dockerfile
    ports:
      - 8000:8000